### ISSUE TITLE
Installation withour Composer

### ISSUE THREAD

**Issue by cniklas** [Highstrike/cakephp-compressor#1]
Hi,
is there a way to install your helper without composer? I don't even see a directory named "lib/vendor/" within my applications directory.

Thanks in advance!
Christian

**Comment by highstrike** [comment]
Sure,

You can download [mrclay's minify](https://github.com/mrclay/minify/releases) and put that in `your-project/app/Vendor` directory. It should look something like this `your-project/app/Vendor/minify-2.2.1`

Afterwards open `your-project/app/Controller/AppController.php` and include the libraries needed. Those are:

```
include(ROOT .DS. 'app' .DS. 'Vendor' .DS. 'minify-2.2.1' .DS. 'min' .DS. 'lib' .DS. 'Minify' .DS. 'HTML.php');
include(ROOT .DS. 'app' .DS. 'Vendor' .DS. 'minify-2.2.1' .DS. 'min' .DS. 'lib' .DS. 'Minify' .DS. 'CSS.php');
include(ROOT .DS. 'app' .DS. 'Vendor' .DS. 'minify-2.2.1' .DS. 'min' .DS. 'lib' .DS. 'Minify' .DS. 'JS' .DS. 'ClosureCompiler.php');
```

I think that should do the trick

**Comment by cniklas** [comment]
Now it works. Thank you!
